version: "3.9"

services:
  db:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: bookstorepass
      MYSQL_DATABASE: bookstoredb
      MYSQL_USER: bookstore
      MYSQL_PASSWORD: bookstorepass
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

  app:
    build: .
    depends_on:
      - db
    environment:
      # Use standard Spring Boot properties instead of DATABASE_URL
      - SPRING_PROFILES_ACTIVE=docker
      - SPRING_DATASOURCE_URL=jdbc:mysql://db:3306/bookstoredb
      - SPRING_DATASOURCE_USERNAME=bookstore
      - SPRING_DATASOURCE_PASSWORD=bookstorepass
    ports:
      # Changed to 8080 for Spring Boot's default port
      - "8080:8080"

volumes:
  db_data: